// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWEsfUiQoIK2Lwz1bhx9xJ5bnDnaHEuA',
    appId: '1:1082178476167:android:83fb2d891485d60bf90022',
    messagingSenderId: '1082178476167',
    projectId: 'stayserene-f36b5',
    databaseURL: 'https://stayserene-f36b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stayserene-f36b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMEkTu9Xfka8DztTyHOeeEur8x-8lNiQ',
    appId: '1:1082178476167:ios:9cb05048c6b2f7b7f90022',
    messagingSenderId: '1082178476167',
    projectId: 'stayserene-f36b5',
    databaseURL: 'https://stayserene-f36b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stayserene-f36b5.appspot.com',
    androidClientId: '1082178476167-4so5grc929m0g14vqpa4qefjekpibdo2.apps.googleusercontent.com',
    iosClientId: '1082178476167-hd1e8lhduqp2ck1mn17vk6428bh36nnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );
}
